### ISSUE TITLE
[FEATURE_REQUEST] Android custom icon theming support

### ISSUE THREAD

**Issue by RustoMCSpit** [mateusz-bak/openreads#284]

**Comment by mateusz-bak** [comment]
Can you say anything more?

**Comment by RustoMCSpit** [comment]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

The monochrome one though especially

**Comment by RustoMCSpit** [comment]
> And what about the monochrome one?

Would be cool if it was implemented, Android has a monochrome only app setting that turns all supporting apps into monochrome form

**Comment by apobrt** [comment]
I think the proposal made in https://github.com/mateusz-bak/openreads-android/issues/315#issuecomment-1670066929 should solve your request

**Comment by mateusz-bak** [comment]
I couldn't properly implement the monochrome icons yet unfortunately. For now I updated icons to the improved ones and after 2.2.0 is released we can look at this again.

Moving this to 2.3.0 milestone.

**Comment by Ribelio** [comment]
Will this be added to the 2.4.0 milestone?

**Comment by mateusz-bak** [comment]
No, I added help wanted label to this issue. If anyone is interested please take a look

**Comment by mateusz-bak** [comment]
@saltsoftdrink you can take a look at icons in this ticket: https://github.com/mateusz-bak/openreads-android/issues/315

And read documentation about monochrome icons in Android and how to implement it in Flutter.

**Comment by sebastien46** [comment]
> I couldn't properly implement the monochrome icons yet unfortunately. For now I updated icons to the improved ones and after 2.2.0 is released we can look at this again.
> 
> ~Moving this to 2.3.0 milestone.~ Removing from the milestone as I didn't figure it out yet.
> 
> Any help welcome!

in #315 , the app icon is always in Bitmap format (as well as in source code), Themed Icon needs to be a VectorDrawable to be Themed, not possible with a Bitmap.
you'd need a source SVG file in order to do that.

**Comment by ikanakova** [comment]
> > I couldn't properly implement the monochrome icons yet unfortunately. For now I updated icons to the improved ones and after 2.2.0 is released we can look at this again.
> > ~Moving this to 2.3.0 milestone.~ Removing from the milestone as I didn't figure it out yet.
> > Any help welcome!
> 
> in #315 , the app icon is always in Bitmap format (as well as in the [source code](https://github.com/mateusz-bak/openreads/blob/master/android/app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png)), Themed Icon needs to be a [VectorDrawable](https://developer.android.com/reference/android/graphics/drawable/VectorDrawable) to be Themed, not possible with a Bitmap. you'd need a source SVG file in order to do that.

Here is the icon converted to svg:
![openreads](https://github.com/mateusz-bak/openreads/assets/38765251/db356d7e-8e7e-4954-92c2-87b822a8c865)

**Comment by ikanakova** [comment]
> Thank you for the svg I didn't find a way to generate svg icons for Android though.
> 
> Flutter package `flutter_launcher_icons` does not support SVGs.
> 
> And when I try to generate new `Image Asset` in Android Studio strictly for Android there is no way to generate the icon as svg (only png and webp). And generating new `Vector Asset` does not generate app's icons.

I think you have to use both in Android Studio - Vector Assets to create a vector drawable from SVG called ic_launcher_foreground (or ic_launcher_monochrome) and then Image Assets to create icons from vector drawable.

**Comment by ikanakova** [comment]
I added the icons #469. I did it in Android Studio, so hopefully it will be OK.

**Comment by mateusz-bak** [comment]
SVGs are creaed here: https://github.com/mateusz-bak/openreads/issues/315#issuecomment-1949917117

**Comment by sebastien46** [comment]
@mateusz-bak I made two VectorDrawables & tried them out in Android Studio:
- Adaptive VectorDrawable icon
- Themed / Monochrome VectorDrawable icon

They turn out pretty nicely imho.
Although, I had to cut the far right part of the text lines on the monochromatic one because they didn't scale nicely.
Please let me know of any criticisms or advice you might have, and I'll make a PR once everything is good.

### Source Adaptive VectorDrawable

![ic_launcher_foreground](https://github.com/mateusz-bak/openreads/assets/57289288/7a48f541-0467-4aa2-ac9a-422dd9acc73c)


### Source Themed VectorDrawable

![ic_launcher_monochrome](https://github.com/mateusz-bak/openreads/assets/57289288/eef4e555-9260-48ed-ae93-4930aaa73008)

## Reference Bitmap Launcher icon

![SCR0_reference](https://github.com/mateusz-bak/openreads/assets/57289288/fb532120-6845-4903-8506-be2c66d6b20b)

## Adaptive VectorDrawable

![SCR1_vectordrawable](https://github.com/mateusz-bak/openreads/assets/57289288/6f0dd9a7-8d05-4239-965d-39d3ad85a23d)

## Themed VectorDrawable, Light Theme, Turquoise Swatch

![SCR2_light_turquoise](https://github.com/mateusz-bak/openreads/assets/57289288/3320387f-a66c-4cd2-957f-6942b40e6e78)

## Themed VectorDrawable, Dark Theme, Turquoise Swatch

![SCR3_dark_turquoise](https://github.com/mateusz-bak/openreads/assets/57289288/51f6b2cc-8817-48da-b6a7-7aa0e07c5ff2)

**Comment by exstntlmsnthrp** [comment]
I definitely give a 👍 for the dark theme version. Looks great.

**Comment by mateusz-bak** [comment]
@sebastien46 this looks great. I think you can create your own PR

**Comment by mateusz-bak** [comment]
> @mateusz-bak bro you've released now 5 version but still not added monochrome icon this guy provided everything but still not

Bro you are welcome to contribute

**Comment by mateusz-bak** [comment]
> > > @mateusz-bak bro you've released now 5 version but still not added monochrome icon this guy provided everything but still not
> > 
> > Bro you are welcome to contribute
> 
> https://youtube.com/shorts/1Spt8r8DfWk?feature=shared

Good starting point, waiting for your PR
